### ISSUE TITLE
Error after last Maya IO update

### ISSUE THREAD

**Issue by M3pI-IIsT0** [zync/zync-maya#5]
Uninstall Zync client and plugins, deleted all remaining files, deleted Maya user folder in documents, restart maya and then PC. Install latest client and maya plugin with correct zync.io address and API keys, run again maya. Run in script zync_maya.submit_dialog()
and get this error
`Error submitting job: https://zyncproject01.zync.io/api/jobs: 500: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 zync-support@google.com to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>`

**Comment by bcipriano** [comment]
Please report this error to zync-support@google.com, they will help you over there.
