### ISSUE TITLE
Installation / Render Job sending Error

### ISSUE THREAD

**Issue by MTOzanne** [zync/zync-maya#7]
Hello, I am  senior at Savannah College of Design and i have my thesis film that i am trying to render. I found ZYNC and from your documentation and the research i have done you are a good resource to have. I have been trying to install the client applications and plug in for a day now and keep getting an error every time no matter if it is a clean scene with no render layers of a clean scene with render layers or the scene that i am looking to submit.  THe error i keep recieving is :  

MayaWindow|SubmitDialog|gridLayout|scrollArea|scrollAreaWidgetContents|layoutWidget|job_type|menuItem280
Collecting render parameters...
Collecting scene info...
# Error: 'NoneType' object has no attribute 'split'
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "D:\zynic_GOOGLERENDERING\zync\zync-maya\zync_maya.py", line 1850, in submit
#     params['layers'].split(','),
# AttributeError: 'NoneType' object has no attribute 'split' # 

If you could help that would be great as i would like to use your service. I am running maya 2015 and trying to render in renderman os win 7 64bit any help would be great. cheers.

**Comment by bcipriano** [comment]
Hi - if you haven't already, could you please report this issue to zync-support@google.com? We handle all support issues through that channel, one of our support team members will get back to you quickly.

Thanks!
